"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Navbar from "@/app/components/navbar/page";
import { GlobalContextProvider } from "./components/globalContext";

import FlashMsg from "./components/flashMsg";

const inter = Inter({ subsets: ["latin"] });

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export default function RootLayout({ children }) {
  return (
    <GlobalContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <Navbar />
          </header>
          <FlashMsg />
          {children}
        </body>
      </html>
    </GlobalContextProvider>
  );
}

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
