export const categoryKeys = {
  gas: { keys: ["speedway", "bp", "shell"], ref: 1 },
  travel: {
    keys: ["valvoline", "ipark", "wifionboard", "uber", "o reilly"],
    ref: 2,
  },
  grocery: { keys: ["kroger", "meijer", "martin"], ref: 3 },
  recFood: {
    keys: [
      "subway",
      "blaze",
      "chick",
      "dairy queen",
      "hacienda",
      "jimmy johns",
      "shake shack",
      "starbucks",
      "lick ice",
      "papa john",
      "shake shack",
      "hacienda",
    ],
    ref: 4,
  },
  school: { keys: [], ref: 5 },
  leisure: {
    keys: [
      "amazon",
      "ausblake",
      "indy city",
      "google",
      "anytime fitness",
      "best buy",
    ],
    ref: 6,
  },
  rent: { keys: [], ref: 7 },
  misc: { keys: ["apple.com", "miscellaneous debit"], ref: 8 },
  income: { keys: ["irving", "indiana univ cons cp", "sbi mobile"], ref: 100 },
  ignore: { keys: ["transfer"], ref: 999 },
  flag: { keys: ["discover"], ref: 400 },
};
